<a href="https://colab.research.google.com/github/Martinmbiro/PyTorch-workflow/blob/main/02%20Building%20a%20PyTorch%20model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Building a PyTorch model**
> ✋ **Info**

> Here, we'll build a standard [`Linear regression`](https://en.wikipedia.org/wiki/Linear_regression) model using PyTorch
+ Familiarity with Python _classes_ is needed to build and train neural networks.
+ Here's a [`resource`](https://realpython.com/python3-object-oriented-programming/) for reference on Python classes

In [ ]:
# import pytorch
import torch, torch.nn as nn
torch.__version__

'2.5.1+cu121'

### Build model

> 📝 **Note**  
+ For this example implementation, [`torch.nn.Parameter`](https://pytorch.org/docs/stable/generated/torch.nn.parameter.Parameter.html#torch.nn.parameter.Parameter) is a kind of Tensor that is to be considered a _module_ parameter
+ Most PyTorch models inherit from the [`torch.nn.Module`](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module) class
+ Building and training neural networks also requires the use of [`torch.optim`](https://pytorch.org/docs/stable/optim.html), [`torch.utils.data.Dataset`](https://pytorch.org/docs/stable/data.html#torch.utils.data.Dataset) & [`torch.utils.data.Dataloader`](https://pytorch.org/docs/stable/data.html)

In [ ]:
# LinearRegressionModel class that sublasses torch.nn.Module
class LinearRegressionModel(nn.Module):
  # we define the model's layers/parameters of our model in the __init__ method
  def __init__(self):
    # call to the parent class must be made before assignment on the child
    super().__init__()
    # scalars to store weight and bias
    self.weight = nn.Parameter(torch.randn(1))
    self.bias = nn.Parameter(torch.randn(1))

  # classes that subclass nn.Module SHOULD override the forward method
  # the forward method specifies the computation in the nn.Module class (model)
  def forward(self, x:torch.Tensor) -> torch.Tensor:
    # m * x + c
    return self.weight * x + self.bias

### Check model contents
> 💎 **Pro Tip**  

> What if we wanted to view the constituents of our model?

In [ ]:
# lets first instantiate our model
# for reproducibility
torch.manual_seed(42)

model_0 = LinearRegressionModel()

#### [`Module.parameters()`](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.parameters)
> Return an _iterator_ over module parameters.  
+ This is typically passed to an optimizer.

In [ ]:
# check type returned
type(model_0.parameters())

generator

In [ ]:
# loop through generator
for i in model_0.parameters():
  print(i)

Parameter containing:
tensor([0.3367], requires_grad=True)
Parameter containing:
tensor([0.1288], requires_grad=True)


#### [`Module.state_dict()`](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.state_dict)
> Return a `dict` containing references to the whole state of the `nn.Module`

In [ ]:
# check type
type(model_0.state_dict())

collections.OrderedDict

In [ ]:
# loop through dictionary
for key, value in model_0.state_dict().items():
  print(f'{key}: {value}')

weight: tensor([0.3367])
bias: tensor([0.1288])


#### [`torchinfo`](https://github.com/TylerYep/torchinfo)
> Provides complementary visualization of the model

In [ ]:
# install the library
!pip install torchinfo
# import summary
from torchinfo import summary

In [ ]:
# we'll pass the shape of our training data (40, 1)
summary(model=model_0, input_size=(40, 1))

Layer (type:depth-idx)                   Output Shape              Param #
LinearRegressionModel                    [40, 1]                   2
Total params: 2
Trainable params: 2
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Inferencing
> To make inference on a model, using [`torch.inference_mode()`](https://pytorch.org/docs/stable/generated/torch.autograd.grad_mode.inference_mode.html#inference-mode) context manager is the recommended way



> 📝 **Note**  
+ Here, we'll make inference on the model with random values, just for demonstration
+ Keep in mind that the model is not yet trained

In [ ]:
# generate some random values
X_test = torch.rand(5, 1)
X_test

tensor([[0.7890],
        [0.2814],
        [0.7886],
        [0.5895],
        [0.7539]])

In [ ]:
# make inference
with torch.inference_mode():
  y_preds = model_0(X_test)

# print predictions
print(y_preds)

tensor([[0.3945],
        [0.2236],
        [0.3943],
        [0.3273],
        [0.3826]])


> ▶️ **Up Next**  

> Training a PyTorch model